const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');
const path = require('path');

// Load backend/.env explicitly so server works even when started from repo root
dotenv.config({ path: path.resolve(__dirname, '.env') });

const { createClient } = require('@supabase/supabase-js');
// Ensure fetch is available on Node (Node 18+ has global fetch). Fallback to node-fetch if needed.
let fetchFn = global.fetch;
try {
  if (!fetchFn) fetchFn = require('node-fetch');
} catch (e) {
  // node-fetch not installed or cannot be required; if global fetch missing, password updates will fail later with clear error
}

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ADMIN_API_KEY = process.env.ADMIN_API_KEY || null; // optional server-only key

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.warn('[backend] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set in .env');
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// bucket used for product images
const PRODUCT_BUCKET = 'product-images';

const app = express();
app.use(cors());
// Allow larger JSON payloads (we accept base64 image uploads from frontend)
app.use(express.json({ limit: '30mb' }));
// Also accept URL-encoded bodies up to same limit
app.use(express.urlencoded({ limit: '30mb', extended: true }));

// Mount payments router (creates orders, momo/vnpay endpoints)
try {
  // const paymentsRouter = require('./routes/payments');
  // // Log incoming payments requests for debugging
  // app.use('/payments', (req, res, next) => {
  //   console.log(`[backend] payments incoming ${req.method} ${req.path}`);
  //   next();
  // }, paymentsRouter);
} catch (err) {
  console.warn('[backend] payments router not available', err && err.message);
}

function requireAdminApiKey(req, res, next) {
  // Require ADMIN_API_KEY to be set in the server environment for admin endpoints.
  // This avoids accidentally exposing admin endpoints when the key isn't configured.
  const key = req.headers['x-admin-api-key'] || req.query.admin_key;
  if (!ADMIN_API_KEY) {
    console.error('[backend] ADMIN_API_KEY is not configured - admin endpoints are disabled');
    return res.status(503).json({ error: 'Admin API key not configured on server' });
  }

  if (key && key === ADMIN_API_KEY) return next();

  return res.status(403).json({ error: 'Forbidden' });
}

// Admin: set role for a user
app.post('/admin/set-role', requireAdminApiKey, async (req, res) => {
  const { user_id, role } = req.body;
  if (!user_id || !role) return res.status(400).json({ error: 'user_id and role required' });

  try {
    const { error } = await supabase.from('profiles').upsert({ id: user_id, role }, { onConflict: 'id' });
    if (error) return res.status(500).json({ error: error.message || error });
    return res.json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: list products (simple proxy to supabase)
app.get('/admin/products', requireAdminApiKey, async (req, res) => {
  try {
    const { data, error } = await supabase.from('products').select('*').order('id', { ascending: true }).limit(100);
    if (error) return res.status(500).json({ error: error.message || error });
    return res.json({ data });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: create or update product (upsert)
app.post('/admin/products', requireAdminApiKey, async (req, res) => {
  const payload = req.body || {};
  // basic validation
  if (!payload || !payload.name) return res.status(400).json({ error: 'product payload with name required' });

  try {
    let result;
    if (payload.id) {
      // upsert when id provided (update or create)
      result = await supabase.from('products').upsert(payload).select();
    } else {
      // insert new product and return the created row (id generated by DB)
      result = await supabase.from('products').insert(payload).select();
    }

    const { data, error } = result;
    if (error) {
      // Log full error details to help diagnose RLS / policy issues
      console.error('[backend] supabase products insert/upsert error', {
        message: error.message || error,
        details: error.details || null,
        hint: error.hint || null,
        code: error.code || null,
        table: 'products',
        payload
      });
      return res.status(500).json({ error: error.message || error, details: error.details || null, code: error.code || null });
    }
    return res.json({ data });
  } catch (err) {
    console.error('[backend] unexpected error in /admin/products', err);
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: upload image via backend (accepts base64 body)
// Accept either JSON { fileName, fileBase64 } or raw octet-stream with header 'x-file-name'
app.post('/admin/upload-image', requireAdminApiKey, async (req, res, next) => {
  // If request has Content-Type: application/octet-stream, we need to parse raw body
  const ct = req.headers['content-type'] || '';
  if (ct.includes('application/octet-stream')) {
    // forward to raw-body handler defined below
    return next();
  }

  // default JSON handling (base64)
  try {
    const { fileName, fileBase64 } = req.body || {};
    if (!fileName || !fileBase64) return res.status(400).json({ error: 'fileName and fileBase64 required' });

    const buffer = Buffer.from(fileBase64, 'base64');
    const filePath = `${Date.now()}_${fileName}`;
    console.log('[backend] uploading image to storage (json)', { bucket: PRODUCT_BUCKET, filePath, size: buffer.length });

    const { error: uploadErr } = await supabase.storage.from(PRODUCT_BUCKET).upload(filePath, buffer, { cacheControl: '3600', upsert: false });
    if (uploadErr) {
      console.error('[backend] storage.upload error', uploadErr);
      return res.status(500).json({ error: uploadErr.message || uploadErr, details: uploadErr.details || null });
    }

    const { data: pub } = supabase.storage.from(PRODUCT_BUCKET).getPublicUrl(filePath);
    const publicUrl = pub?.publicUrl || null;
    return res.json({ publicUrl });
  } catch (err) {
    console.error('[backend] /admin/upload-image error (json)', err);
    return res.status(500).json({ error: err.message || err });
  }
});

// Raw octet-stream handler for large files
app.post('/admin/upload-image', requireAdminApiKey, express.raw({ type: 'application/octet-stream', limit: '50mb' }), async (req, res) => {
  try {
    const fileName = req.headers['x-file-name'] || req.query.fileName;
    if (!fileName) return res.status(400).json({ error: 'x-file-name header or fileName query required' });
    const buffer = Buffer.from(req.body);
    const filePath = `${Date.now()}_${String(fileName).replace(/[^a-zA-Z0-9_.-]/g, '_')}`;
    console.log('[backend] uploading image to storage (octet-stream)', { bucket: PRODUCT_BUCKET, filePath, size: buffer.length });

    const { error: uploadErr } = await supabase.storage.from(PRODUCT_BUCKET).upload(filePath, buffer, { cacheControl: '3600', upsert: false });
    if (uploadErr) {
      console.error('[backend] storage.upload error (octet-stream)', uploadErr);
      return res.status(500).json({ error: uploadErr.message || uploadErr, details: uploadErr.details || null });
    }

    const { data: pub } = supabase.storage.from(PRODUCT_BUCKET).getPublicUrl(filePath);
    const publicUrl = pub?.publicUrl || null;
    return res.json({ publicUrl });
  } catch (err) {
    console.error('[backend] /admin/upload-image error (octet)', err);
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: delete product
app.delete('/admin/products/:id', requireAdminApiKey, async (req, res) => {
  const id = req.params.id;
  try {
    const { error } = await supabase.from('products').delete().eq('id', id);
    if (error) return res.status(500).json({ error: error.message || error });
    return res.json({ ok: true });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: create profile
app.post('/admin/profiles', requireAdminApiKey, async (req, res) => {
  try {
    const { email, password, full_name } = req.body;
    if (!email || !password) return res.status(400).json({ error: 'email and password required' });
    
    // Create user in auth
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password,
      user_metadata: { full_name }
    });
    if (authError) return res.status(500).json({ error: authError.message || authError });
    
    // Upsert profile
    const { data: profileData, error: profileError } = await supabase.from('profiles').upsert({ 
      id: authData.user.id, 
      full_name, 
      email 
    }).select();
    if (profileError) return res.status(500).json({ error: profileError.message || profileError });
    
    return res.json({ data: profileData });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: list profiles
app.get('/admin/profiles', requireAdminApiKey, async (req, res) => {
  try {
    const { data, error } = await supabase.from('profiles').select('*').order('updated_at', { ascending: false });
    if (error) return res.status(500).json({ error: error.message || error });
    return res.json({ data });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: update profile
app.put('/admin/profiles/:id', requireAdminApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { full_name, email, password } = req.body;
    console.log('[backend] update profile', { id, full_name, email, hasPassword: !!password });

    // Update profile row
    const { data, error } = await supabase.from('profiles').update({ full_name, email }).eq('id', id).select();
    if (error) {
      console.error('[backend] profiles.update error', error);
      return res.status(500).json({ error: error.message || error });
    }

    // If password provided, call Supabase Admin REST API to update user's password
    if (password) {
      if (!SUPABASE_SERVICE_ROLE_KEY || !SUPABASE_URL) {
        console.error('[backend] cannot update password - service role key or url missing');
        return res.status(500).json({ error: 'Server missing Supabase service role key or URL' });
      }

      const updateUrl = `${SUPABASE_URL.replace(/\/$/, '')}/auth/v1/admin/users/${id}`;
      try {
        console.log('[backend] calling supabase admin REST to update password for', id);
        const updateResponse = await fetchFn(updateUrl, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
            'apikey': SUPABASE_SERVICE_ROLE_KEY,
          },
          body: JSON.stringify({ password }),
        });

        if (!updateResponse.ok) {
          const errorText = await updateResponse.text();
          console.error('[backend] supabase admin update failed', updateResponse.status, errorText);
          return res.status(500).json({ error: `Failed to update password: ${errorText}` });
        }

        const updateData = await updateResponse.json();
        console.log('[backend] password updated successfully', updateData);
      } catch (e) {
        console.error('[backend] error calling supabase admin REST', e);
        return res.status(500).json({ error: e.message || e });
      }
    }

    return res.json({ data });
  } catch (err) {
    console.error('[backend] update profile error', err);
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: delete profile
app.delete('/admin/profiles/:id', requireAdminApiKey, async (req, res) => {
  try {
    const { id } = req.params;
    const { error } = await supabase.from('profiles').delete().eq('id', id);
    if (error) return res.status(500).json({ error: error.message || error });
    return res.json({ success: true });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

// Admin: monthly reports (income/estimate) based on cart rows
app.get('/admin/reports/monthly', requireAdminApiKey, async (req, res) => {
  try {
    const year = Number(req.query.year) || new Date().getFullYear();
    const month = Number(req.query.month) || (new Date().getMonth() + 1); // 1-12

    // compute start/end in ISO
    const start = new Date(Date.UTC(year, month - 1, 1)).toISOString();
    const end = new Date(Date.UTC(year, month, 1)).toISOString();

    // fetch cart rows within timeframe and embed variant + product
    const { data, error } = await supabase
      .from('cart')
      .select(`id,quantity,created_at,variant:product_variants(id,price_vnd,product:products(id,name,price))`)
      .gte('created_at', start)
      .lt('created_at', end);

    if (error) return res.status(500).json({ error: error.message || error });

    const rows = data || [];

    // Helper to parse product.price string like "1.299.000đ"
    const parsePrice = (p) => {
      if (!p) return 0;
      if (typeof p === 'number') return p;
      try {
        return Number(String(p).replace(/[^\d]/g, '')) || 0;
      } catch (e) { return 0; }
    };

    // Aggregate totals and per-day breakdown
    const totals = { revenue: 0, items: 0 };
    const byDay = {}; // YYYY-MM-DD -> { revenue, items }

    for (const r of rows) {
      const qty = Number(r.quantity) || 0;
      const variant = r.variant || null;
      const unit = (variant && (variant.price_vnd || parsePrice(variant.product?.price))) || 0;
      const rev = unit * qty;
      totals.revenue += rev;
      totals.items += qty;

      const day = r.created_at ? new Date(r.created_at).toISOString().slice(0,10) : 'unknown';
      if (!byDay[day]) byDay[day] = { revenue: 0, items: 0 };
      byDay[day].revenue += rev;
      byDay[day].items += qty;
    }

    // format byDay as array
    const breakdown = Object.keys(byDay).sort().map(d => ({ day: d, ...byDay[d] }));

    return res.json({ ok: true, period: { year, month }, totals, breakdown, rowsCount: rows.length });
  } catch (err) {
    return res.status(500).json({ error: err.message || err });
  }
});

const port = process.env.PORT || 54321;
console.log('[backend] Starting server on port', port);
app.listen(port, () => console.log(`[backend] admin server listening on ${port}`));
